My second hw commit
Vidhya-eng/redi_js_spring_2020 pull request #6
Opened 2020-04-06 23:02 UTC by Vidhya-eng

New files

2020-04-13 09:29 UTC, MrTim requested changes
Nice work! 
there are some comment regarding styling - which is important as well. So please fix those comments.

2020-04-13 09:29 UTC, MrTim commented on Lesson3.html
> +
not needed empty line.

2020-04-13 09:29 UTC, MrTim commented on Lesson3.html
> +            goodButtonCmp.addEventListener("click",goodButtonClick);
it's better to put space after comma. That was separation looks better:
`            goodButtonCmp.addEventListener("click", goodButtonClick);`

2020-04-13 09:29 UTC, MrTim commented on Lesson3.html
> +            function goodButtonClick(event){
`function goodButtonClick(event) {` - space before curly bracket

2020-04-13 09:29 UTC, MrTim commented on Lesson3.html
> +                answerCmp.textContent= "That's great 😃"
do not omit `;` at the end of statement. Think about it as required to have.
Check your code for that missing semicolon.

2020-04-13 09:29 UTC, MrTim commented on index.html
> +                <button id="burgerBtn"><i class="fa fa-bars"></i></button>
:+1:

2020-04-13 09:29 UTC, MrTim commented on index.html
> +
not needed empty line. And below your using `<br/>` which is not needed. You should be able to achieve the same with css styles.

2020-04-13 09:29 UTC, MrTim commented on index.html
> +
Empty line

2020-04-13 09:29 UTC, MrTim commented on style.css
> +
Empty line :) 
Check the code below for not needed empty lines.
I personally  do one empty line as separator between css classes. This increase readability of the code.

2020-04-13 09:29 UTC, MrTim commented on style.css
> +.Section{
camelCase - should be `.section {`

2020-04-19 14:14 UTC, aberezhk approved these changes
All good. Please merge.

2020-04-19 14:14 UTC, aberezhk commented on Lesson3.html
> +<html>
Good job! Could you please add navigation and footer bars from index.html to this page as well?
Later we will link all pages in one project. So they all should have same header and footer.

2020-04-20 07:57 UTC, Vidhya-eng commented on Lesson3.html
> +<html>
i didnt understand.Do you mean ,,,i should add a navigation bar and a footer to this lesson3.html

2020-04-20 13:15 UTC, merged